# Generated by Django 2.1.3 on 2018-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email_contact', models.CharField(max_length=30)),
                ('phone_contact', models.CharField(max_length=30)),
            ],
        ),
    ]
