# Generated by Django 2.1.3 on 2018-12-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassign',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In progress'), ('failed', 'Failed'), ('passed', 'Passed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Organization'),
        ),
    ]
