# Generated by Django 2.1.3 on 2018-12-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tests_result',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='error',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='line',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='teacher_comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='error',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='line',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In progress'), ('failed', 'Failed'), ('passed', 'Passed')], default='TR', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works.Task'),
            preserve_default=False,
        ),
    ]
