# Generated by Django 2.1.3 on 2018-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='file',
            field=models.FileField(default='yest', upload_to=''),
            preserve_default=False,
        ),
    ]
