# Generated by Django 2.0.2 on 2018-12-01 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassign',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('value_type', 'Value type check'), ('value_equals', 'Value equals')], default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
