# Generated by Django 2.0.2 on 2018-12-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20181201_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default='test', upload_to='reports/'),
            preserve_default=False,
        ),
    ]
