# Generated by Django 2.0.2 on 2018-12-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20181201_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='task',
        ),
        migrations.AddField(
            model_name='test',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='works.Task'),
            preserve_default=False,
        ),
    ]
