# Generated by Django 2.0.2 on 2018-12-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20181201_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='task',
        ),
        migrations.AddField(
            model_name='report',
            name='passed',
            field=models.NullBooleanField(),
        ),
    ]
