# Generated by Django 2.0.2 on 2018-12-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20181201_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='passed',
            field=models.NullBooleanField(),
        ),
    ]
