# Generated by Django 2.0.2 on 2018-12-02 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_testresult_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='works.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassign',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskslist',
            name='name',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='teacher_comment',
            field=models.TextField(null=True),
        ),
    ]
